# Generated by Django 4.1.7 on 2023-06-07 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_ja', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_es', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_pt', models.CharField(db_index=True, max_length=50, unique=True)),
                ('approved_en', models.BooleanField(default=False)),
                ('approved_ja', models.BooleanField(default=False)),
                ('approved_es', models.BooleanField(default=False)),
                ('approved_pt', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ctag',
                'verbose_name_plural': 'ctags',
                'ordering': (django.db.models.functions.text.Lower('name_en'),),
            },
        ),
        migrations.CreateModel(
            name='CTagAliasEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField(verbose_name='target ctag id')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('ctag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ctags.ctag', verbose_name='ctag')),
            ],
            options={
                'verbose_name': 'tagged item',
                'verbose_name_plural': 'tagged items',
                'unique_together': {('ctag', 'content_type', 'object_id')},
            },
        ),
    ]
